### ISSUE TITLE
Fonts missing on mac os 10.12.5

### ISSUE THREAD

**Issue by oded-rosi** [yossij/dotfiles#1]
<img width="1116" alt="screen shot 2017-07-13 at 12 03 07" src="https://user-images.githubusercontent.com/12557824/28158761-76dd0858-67c3-11e7-9168-e130b42208e1.png">

? instead of the regular zsh

**Comment by YJ-AllCloud** [comment]
Hi oded-rosi,
Thank you for pointing out the issue.
I've update the info for iTerm users.
Please try and feedback
